FROM python:3.10-alpine

WORKDIR /homework_11

COPY requirements.txt .

RUN pip install -U pip
RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT ["pytest"]

FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt update && apt install -y python3 python3-pip git